-- 코드를 작성해주세요
SELECT I.ID,N.FISH_NAME,I.LENGTH FROM FISH_INFO I 
JOIN FISH_NAME_INFO N
ON I.FISH_TYPE = N.FISH_TYPE
WHERE I.LENGTH = (SELECT MAX(LENGTH) FROM FISH_INFO WHERE FISH_TYPE = I.FISH_TYPE)
ORDER BY I.ID ASC;

# 서로 다른 종류의 물고기가 우연히 같은 최대 길이를 가지면, GROUP BY 때문에 둘 중 하나가 증발하여 데이터가 유실된다.